/**
 * Nombres "Material Symbols" usados en el mockup (ui-shared/plantilla.html). Fuente
 * de verdad del tipo `nombre` de <Icono />, compartida entre `Icono.tsx` (mobile,
 * @expo/vector-icons) e `Icono.web.tsx` (web, webfont Material Symbols real).
 */
export type NombreSimbolo =
  | "account_balance"
  | "account_balance_wallet"
  | "add"
  | "add_circle"
  | "alarm"
  | "arrow_forward"
  | "article"
  | "assignment_turned_in"
  | "badge"
  | "bolt"
  | "calendar_today"
  | "category"
  | "check_circle"
  | "chevron_right"
  | "close"
  | "content_copy"
  | "description"
  | "domain"
  | "done_all"
  | "download"
  | "electric_bolt"
  | "error"
  | "event_repeat"
  | "expand_more"
  | "flip"
  | "forward_to_inbox"
  | "health_and_safety"
  | "lock"
  | "lock_clock"
  | "lock_open"
  | "logout"
  | "notifications"
  | "payments"
  | "person"
  | "picture_as_pdf"
  | "public"
  | "qr_code_2"
  | "qr_code_scanner"
  | "receipt"
  | "receipt_long"
  | "refresh"
  | "savings"
  | "school"
  | "security"
  | "security_update_good"
  | "send"
  | "shield"
  | "speed"
  | "support_agent"
  | "swap_horiz"
  | "sync"
  | "sync_alt"
  | "tag"
  | "trending_up"
  | "tune"
  | "update"
  | "verified"
  | "verified_user"
  | "visibility"
  | "visibility_off"
  | "wifi";
